spring:
    application:
        name: "configserver"
    profiles:
        #active: native # to be used with classpath and file system locations
        active: git
    cloud:
        config:
            server:
              #native:
                # search-locations: "classpath:/config"
                # search-locations: "file:///C://Users//ManjuAni//Documents//configserver-local"
              git:
                uri: https://github.com/eazybytes/eazybytes-config.git
                default-label: main
                timeout: 5
                clone-on-start: true
                force-pull: true

server:
  port: 8071
