services:
  accounts:
    image: "premv8903/accounts:s4"  # <dockerhub_username>/<image_name>:<tag>
    container_name: accounts-ms     # if no name is given, a random name will be generated and used
    ports:
      - "8080:8080"                 # <local system host_port>:<docker container_port>
    deploy:
      resources:
        limits:
          memory: 700m               # Provide a max of 700 MB of memory to this container
    networks:
      - eazybank
  loans:
    image: "premv8903/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  cards:
    image: "premv8903/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
networks:
  eazybank:           # same network name is used in the accounts, loans and cards microservices at line nos: 12, 23, 34
    driver: "bridge"  # create a network with the name eazybank with the driver bridge
                      # Since I'm using the same network inside my accounts, loans and the cards microservices.
                      # My Docker server is going to establish a bridge using which all my microservices can communicate with each other.